### ISSUE TITLE
get `undefined: syscall.Stat_t` when use quic in the windows environment

### ISSUE THREAD

**Issue by wenchaopeng** [libp2p/go-libp2p-quic-transport#82] opened 2019-11-12 09:18 UTC
I have a problem with quic in the windows environment
 my code is like this:
```
        sourceMultiAddr, _ := ma.NewMultiaddr(node.cfg.P2P.Listen)
	q,err:=quic.NewTransport(node.privateKey)
	if err!=nil{
		return err
	}
	host, err := libp2p.New(
		node.ctx,
		libp2p.ListenAddrs(sourceMultiAddr),
		libp2p.Identity(node.privateKey),
		libp2p.BandwidthReporter(node.reporter),
		libp2p.Ping(false),
		libp2p.Transport(q),
	)
	if err != nil {
		return err
	}
```

the error log is like this：
```
# github.com/vishvananda/netns
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:27:13: undefined: syscall.Stat_t
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:28:12: undefined: syscall.Fstat
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:31:12: undefined: syscall.Fstat
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:39:8: undefined: syscall.Stat_t
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:43:12: undefined: syscall.Fstat
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:52:8: undefined: syscall.Stat_t
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:56:12: undefined: syscall.Fstat
D:\goproject\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:70:29: cannot use int(*ns) (type int) as type syscall.Handle in argument to syscall.Close
```
pls help me,thanks you!

**Comment by marten-seemann** [comment] 2019-11-13 02:46
It seems like [netlink](https://github.com/vishvananda/netlink) doesn't support Windows, there's even a (three years old) issue for that: https://github.com/vishvananda/netlink/issues/146. I confirmed that it's not possible to build it on Windows.

The only fix for this I can think of is to not even import netlink on Windows. This won't be a trivial thing though, since `reuse` contains a `netlink.Handle`, and it's expected to be `nil` on non-Linux systems, it will still pull in netlink and cause the build error.
So we'd probably have to refactor `reuse` in a base struct that works on all OSes, and extend this struct with the netlink capabilities in a struct that's only built on Linux on OSX.

I'm quite busy at the moment and won't have time to work on this any time soon, but I'd be happy to review a PR.

**Comment by wenchaopeng** [comment] 2019-11-13 05:56
Roger that

**Comment by Stebalien** [comment] 2019-11-14 18:39
This is making it impossible to update QUIC in libp2p/go-ipfs which is preventing us from deploying it to infra.

**Closed** 2019-11-15 13:14 UTC
Labels: P1 - High
